/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetParcelRequest extends SpeakeasyBase {
    /**
     * ID of the parcel to retrieve
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=parcel_id" })
    parcelId: string;
}

export class GetParcelResponse extends SpeakeasyBase {
    /**
     * Bad Request
     */
    @SpeakeasyMetadata()
    badRequest?: shared.BadRequest;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    parcel?: shared.Parcel;

    /**
     * Server Error
     */
    @SpeakeasyMetadata()
    serverError?: shared.ServerError;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Unauthorized
     */
    @SpeakeasyMetadata()
    unauthorized?: shared.Unauthorized;
}
